### ISSUE TITLE
Separate filter building and read classification

### ISSUE THREAD

**Issue by mptrsen** [jlanga/exfi#70]
Currently, `build_baited_bloom_filter` does both the filter building *and* read classification (despite its name). Even though filter building is quite fast, it would be prudent to be able to re-use one filter for multiple read datasets. Perhaps add an option to only build the filter, and allow to specify a pre-existing filter?

**Comment by jlanga** [comment]
That's the plan: to use the transcriptome as bait to filter reads, and insert it into a brand new bloom filter, made of exonic reads only. It is a python wrapper for bbt and abyss. If you are only interested in classifying reads, bbt is the tool you want. You can filter your reads however you wanted and later on pass them to exfi.

A transcriptomic filter only takes seconds and a few hundred megabytes. We chose to remove it because it was fast and to not pollute the file system. The Bloom filter you are interested in is the genomic one. Also, bbt chooses for you the optimal parameters. They may change between runs.
